// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // Same config as iOS
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2SQHUJhVoJY9Q_UfVvbqBmPACY13AWw',
    appId: '1:944816607785:web:20a318932d336d6257c238',
    messagingSenderId: '944816607785',
    projectId: 'vault-29d9e',
    authDomain: 'vault-29d9e.firebaseapp.com',
    storageBucket: 'vault-29d9e.firebasestorage.app',
    measurementId: 'G-Y1FEDK17J1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBe5pdq9UJQw56ZqwDspyIJeBujsOGz4Q',
    appId: '1:944816607785:ios:ae86c7b61bed808d57c238',
    messagingSenderId: '944816607785',
    projectId: 'vault-29d9e',
    storageBucket: 'vault-29d9e.firebasestorage.app',
    iosBundleId: 'com.vault.app',
  );
}
